apiVersion: v1
kind: Pod
metadata:
  name: pod-all
  labels:
    app: pod-all
spec:
  initContainers:
  - name: init-myservice
    image: nginx
    command: ['sh', '-c', 'sleep 2; echo helloworld01;']
  - name: init-mydb
    image: nginx
    command: ['sh', '-c', 'sleep 2; echo helloworld02;']
  containers:
  - name: pod-all
    image: nginx
    resources:
      requests:
        cpu: 0.1
        memory: 200M
      limits:
        cpu: 0.5
        memory: 1G
    ports:
    - containerPort: 8080
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    env:
    - name: TESTENV01
      value: "testvalue01" # 첫 번째 환경 변수
    - name: HOSTNAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName # 두 번째 환경 변수
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name  # 세 번째 환경 변수
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP # 네 번째 환경 변수
    - name: CPU_REQUEST
      valueFrom:
        resourceFieldRef:
          containerName: pod-all
          resource: requests.cpu # 다섯 번째 환경 변수
    - name: CPU_LIMIT
      valueFrom:
        resourceFieldRef:
          containerName: pod-all
          resource: limits.cpu # 여섯 번째 환경 변수
