apiVersion: v1
kind: Pod
metadata:
  name: pod-resource
  labels:
    app: pod-resource
spec:
  containers:
  - name: pod-resource
    image: nginx
    resources:
      requests:
        cpu: 0.1
        memory: 200M
      limits:
        cpu: 0.5
        memory: 1G
    ports:
    - containerPort: 8080