apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Mi
  hostPath:
    path: /opt/data
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
