apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: taint-test
  name: taint-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taint-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: taint-test
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
