apiVersion: v1
kind: Pod
metadata:
  name: kubernetes-nodeselector-pod
spec:
  containers:
  - name: kubernetes-nodeselector-pod
    image: nginx
    ports:
    - containerPort: 8080
  nodeSelector:
    disktype: hdd