apiVersion: v1
kind: Pod
metadata:
  name: volume-emptydir
spec:
  containers:
  - name: volume-emptydir
    image: nginx
    volumeMounts:
    - mountPath: /emptydir
      name: emptydir-vol
    # ports:
    # - containerPort: 8080
  volumes:
  - name: emptydir-vol
    emptyDir: {}
